import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				style={{ background: "black" }}
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<nav
					style={{
						display: "flex",
						width: "100%",
						alignItems: "center",
						justifyContent: "center",
						fontSize: "30px",
						background: "#ccc",
					}}
				>
					<Link
						style={{ margin: "3px", textDecoration: "underline" }}
						href="/posts"
					>
						Posts
					</Link>
					<Link
						style={{ margin: "3px", textDecoration: "underline" }}
						href="/"
					>
						{" "}
						Users{" "}
					</Link>
				</nav>
				{children}
			</body>
		</html>
	);
}
